template-engine:
  main:
    consumer:
      assign_offset_end: true
      conf:
        auto.commit.interval.ms: 1000
        bootstrap.servers: "localhost:9092"
        debug: all
        default.topic.config:
          auto.offset.reset: largest
        enable.auto.commit: true
        enable.auto.offset.store: false
        group.id: dialog_policy1
        session.timeout.ms: 6000
        topic.metadata.refresh.interval.ms: 100000
      internal_log_path: /tmp
      poll_timeout: 0.01
      topics:
        apps: toTestApp
    publisher:
      conf:
        bootstrap.servers: "localhost:9092"
        topic.metadata.refresh.interval.ms: 100000
      flush_timeout: 10000
      partitions_count: 3
      poll_timeout: 0.01
      topic:
        apps: fromTestApp
